[tool.poetry]
name = "crispy-forms-gds"
version = "0.2.2"
description = "A GOV.UK Design System template pack for django-crispy-forms."
authors = ["Wildfish <developers@wildfish.com>", "Department for International Trade <webops@digital.trade.gov.uk>"]
license = "BSD 3-clause License"
readme = "README.rst"
homepage = "https://github.com/uktrade/crispy-forms-gds"
repository = "https://github.com/uktrade/crispy-forms-gds"
keywords = ["crispyforms", "gds", "django"]

[tool.poetry.dependencies]
python = "^3.8"
django-crispy-forms = ">=1.9.0"
django = ">=2.2"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
